language: java
jdk:
  - oraclejdk10
script:
- echo "Updating to the latest AWS JDK....."
- bash upgrade-sdk.sh
- echo "Compiling and packaging Cloud Explorer....."
- ant
- mkdir $HOME/build/rusher81572/cloudExplorer/cloudExplorer
- cp -rf dist/* cloudExplorer
- zip --exclude=*.git* -r cloudExplorer-$VERSION.zip cloudExplorer
- echo "Starting functional testing......"
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar listbuckets
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar makebucket $TESTBUCKET us-east-2
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar makebucket $MIGRATE_BUCKET us-west-1
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar makebucket $SNAPSHOT_BUCKET ca-central-1
#- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar createfolder $TESTBUCKET synctest
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar synctos3 $HOME/build/rusher81572/cloudExplorer/src $TESTBUCKET synctest
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar ls $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar syncfroms3 /tmp $TESTBUCKET synctest
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar synctos3 /tmp/synctest $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar syncfroms3 /tmp $TESTBUCKET synctest
- ls /tmp/synctest/src/cloudExplorer
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar search $TESTBUCKET png
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar migrate $TESTBUCKET $MIGRATE_BUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar migrate $MIGRATE_BUCKET $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar snapshot $TESTBUCKET $SNAPSHOT_BUCKET
- echo > /tmp/synctest/src/cloudExplorer/Abort.java
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar synctos3 /tmp/synctest $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar snapshot $TESTBUCKET $SNAPSHOT_BUCKET Snapshot-$TESTBUCKET-`date +"%Y-%m-%d"`
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar uploadtest $TESTBUCKET 10 10 10 mixed
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar download $TESTBUCKET 10 10 10 mixed
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar deleteall $MIGRATE_BUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar deleteall $SNAPSHOT_BUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar deleteall $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar rmbucket $TESTBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar rmbucket $SNAPSHOT_BUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar rmbucket $MIGRATE_BUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar build $VERSION/cloudExplorer-$VERSION.zip $HOME/build/rusher81572/cloudExplorer/cloudExplorer-$VERSION.zip $PUBBUCKET
- java -jar $HOME/build/rusher81572/cloudExplorer/dist/CloudExplorer.jar build cloudExplorer-dev.zip $HOME/build/rusher81572/cloudExplorer/cloudExplorer-$VERSION.zip $PUBBUCKET
